language: scala
dist: trusty

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache


jdk:
  - oraclejdk8
scala:
  - 2.11.8

addons:
  sonarcloud:
    organization: "thec0dewriter-github"



script:
  - sbt clean coverage test coverageReport
  - sbt scalastyle scapegoat
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: false

